### ISSUE TITLE
Jpg sequence question

### ISSUE THREAD

**Issue by ArtemSh-Hd** [Rainbox-dev/DuME#180] opened 2020-09-05 17:09 UTC
**Describe the bug**
An attempt to add a Jpg sequence leads to an incomprehensible result

**To Reproduce**
1. I reset the program settings to their default values and removed the Cyrillic characters from the file path (just in case)
2. Drag and drop sequence [1 ... 199] or [001 ... 199] or tried to enter in the address bar "../name{###}"
3. I tried to render regardless of interface inaccuracies

**Error description, if any**
At the beginning strange information appeared, then when renamed [001 ... 199] the information disappeared altogether. Sequence information was not displayed in the Input section, but an input field for FPS appeared. Miscalculation did not take place

**Expected behavior**
Waited for information to appear in the Input section and the result of the calculation by pressing the render button

**Screenshots**
![1unknown](https://user-images.githubusercontent.com/69811802/92310015-ebf2da80-efb2-11ea-95d6-016ef0a4ed27.png)
![2unknown](https://user-images.githubusercontent.com/69811802/92310016-ed240780-efb2-11ea-9fbd-b749a9ea389a.png)
![3Screenshot_1](https://user-images.githubusercontent.com/69811802/92310017-ed240780-efb2-11ea-8fb3-a021ce94f83a.png)
![4unknown](https://user-images.githubusercontent.com/69811802/92310018-edbc9e00-efb2-11ea-9559-1c93c5079c11.png)

**System (please complete the following information):**
 - Version of the OS: Windows 10
 - Version of DuME: DuME v0.1.3-RC

**Additional context**
Thanks for your work. Thanks to you, I changed my views and met Patreon! Sorry for my english. I used google translate.

**Comment by Nico-Duduf** [comment] 2020-09-06 17:23
The issue is fixed in the next version of DuME, available soon

**Closed** 2020-09-06 17:22 UTC
Labels: bug
